services:
  db:
    image: postgres:15
    container_name: postgres-data-automation
    restart: always
    environment:
      POSTGRES_USER: user_dev
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: data_automation_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: